In [5]:
import pandas as pd
import numpy as np
infile = 'Extra_Raw_Data/Hospital_General_Information.csv'

In [4]:
hospital_df = pd.read_csv(infile)

FileNotFoundError: File b'../Extra_Raw_Data/Hospital_General_Information.csv' does not exist

In [ ]:
hospital_df.head()

In [13]:
hosp_grp = hospital_df.groupby(['State','County Name'])[['Hospital Name']].count()

In [14]:
hosp.grp.head()

                               Hospital Name
State County Name
AK    ANCHORAGE                            3
      BETHEL                               1
      DILLINGHAM                           1
      FAIRBANKS NORTH STAR                 1
      JUNEAU                               1
      KENAI PENINSULA                      3
      KETCHIKAN GATEWAY                    1
      KODIAK ISLAND BOROUGH                1
      MATANUSKA-SUSITNA                    1
      NOME                                 1
      NORTHWEST ARTIC BOROUGH              1
      SITKA BOROUGH                        2
AL    AUTAUGA                              1
      BALDWIN                              3
      BARBOUR                              1
      BIBB                                 1
      BLOUNT                               1
      BULLOCK                              1
      BUTLER                               2
      CALHOUN                              3
      CHEROKEE                             1
      CHILTON                              1
      CHOCTAW                              1
      CLARKE                               2
      CLAY                                 1
      COFFEE                               1
      COLBERT                              2
      CONECUH                              1
      COVINGTON                            2
      CRENSHAW                             1
...                                      ...
WV    ROANE                                1
      SUMMERS                              1
      TAYLOR                               1
      TYLER                                1
      UPSHUR                               1
      WEBSTER                              1
      WETZEL                               1
      WOOD                                 1
WY    ALBANY                               1
      BIG HORN                             2
      CAMPBELL                             1
      CARBON                               1
      CONVERSE                             1
      CROOK                                1
      FREMONT                              1
      GOSHEN                               1
      HOT SPRINGS                          1
      JOHNSON                              1
      LARAMIE                              1
      LINCOLN                              2
      NATRONA                              3
      NIOBRARA                             1
      PARK                                 2
      PLATTE                               1
      SHERIDAN                             1
      SWEETWATER                           2
      TETON                                1
      UINTA                                1
      WASHAKIE                             1
      WESTON                               1

[2486 rows x 1 columns]

In [15]:
# Write to new CSV
hosp_grp.to_csv('Hospital_Count_by_County.csv')